Write-Host "Script code, generated by XIE"
$paths = @("C:\Windows\Temp", "C:\Users\$env:UserName\AppData\Local\Temp", "C:\Windows\Prefetch")

function Remove-TempFiles {
    param (
        [string]$path
    )
    Write-Host "Dang xoa file rac trong $path"
    Get-ChildItem -Path $path -Recurse -Force | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
}

foreach ($path in $paths) {
    Remove-TempFiles -path $path
}

Write-Host "Dang xoa trong Recycle Bin"
$shell = New-Object -ComObject Shell.Application
$recycleBin = $shell.Namespace(0xA)
$recycleBin.Items() | %{Remove-Item $_.Path -Recurse -Force}
Write-Host "Hoan thanh xong cong viec !!"
